// Generated by Cactus DSL Compiler (cpp-entt backend)
#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <entt/entt.hpp>
#include "raylib.h"

inline Vector2 vec2(float x, float y) { return {x, y}; }

enum class FacingDirection {
    Left,
    Right
};

enum class JumpState {
    Grounded,
    Jumping,
    Falling,
    WallSliding
};

enum class PlatformType {
    Ground,
    Floating,
    Wall
};

enum class EnemyType {
    Walker,
    Flyer
};

enum class GemType {
    Blue,
    Gold
};

struct Platform {
    Vector2 plat_pos{};
    Vector2 plat_size{};
    PlatformType platform_type{};
    Color plat_color{};
};

struct Position {
    Vector2 pos{};
    Vector2 velocity{};
};

struct Collectible {
    int point_value{};
    GemType gem_type{};
    Color gem_color{};
    float gem_size{};
    bool collected{};
};

struct PlayerPhysics {
    float gravity{};
    float jump_force{};
    bool is_grounded{};
    int jumps_remaining{};
    int max_jumps{};
    float wall_slide_speed{};
};

struct PlayerController {
    float move_speed{};
    FacingDirection facing{};
    JumpState jump_state{};
    float width{};
    float height{};
};

struct Health {
    int health{};
    int lives{};
    int max_health{};
    float invincible_timer{};
};

struct EnemyAI {
    float patrol_min_x{};
    float patrol_max_x{};
    float patrol_speed{};
    float direction{};
    EnemyType enemy_type{};
    Color enemy_color{};
    float enemy_width{};
    float enemy_height{};
};

struct Score {
    int score{};
    int gems_collected{};
};

struct SideScrollCamera {
    float cam_x{};
    float cam_y{};
    float offset_x{};
    float offset_y{};
    float smoothing{};
    float min_x{};
    float max_x{};
    float parallax_far{};
    float parallax_mid{};
};

struct PlayerJumpedEvent {
    int position;
    int jumps_remaining;
};

struct PlayerLandedEvent {
    int position;
};

struct PlayerDamagedEvent {
    int amount;
};

struct PlayerDiedEvent {
    int lives_remaining;
};

struct PlatformCollisionEvent {
    int entity;
    int platform_pos;
    int platform_size;
    float overlap_x;
    float overlap_y;
};

struct EnemyDefeatedEvent {
    int position;
};

struct GemCollectedEvent {
    int point_value;
    int gem_type;
    int position;
};

// ── Persist Serialization ────────────────────────────────────────────

void save_Position(const Position& comp) {
    // serialize comp.pos
}

void load_Position(Position& comp) {
    // deserialize into comp.pos
}

void save_Health(const Health& comp) {
    // serialize comp.health
    // serialize comp.lives
}

void load_Health(Health& comp) {
    // deserialize into comp.health
    // deserialize into comp.lives
}

void save_Score(const Score& comp) {
    // serialize comp.score
    // serialize comp.gems_collected
}

void load_Score(Score& comp) {
    // deserialize into comp.score
    // deserialize into comp.gems_collected
}

// ── Sync Replication ─────────────────────────────────────────────────

void replicate_Position(const Position& comp) {
    // send delta for comp.pos
}

void replicate_Health(const Health& comp) {
    // send delta for comp.health
}

// ── Systems ─────────────────────────────────────────────────────────

void MovementSystem_tick(entt::registry& registry, float dt) {
    auto view = registry.view<Position, PlayerController>();
    view.each([&](auto& Position_comp, auto& PlayerController_comp) {
        auto input_x = get_input_axis_x();
        if ((input_x > 0.0f)) {
            PlayerController_comp.facing = FacingDirection::Right;
        }
        if ((input_x < 0.0f)) {
            PlayerController_comp.facing = FacingDirection::Left;
        }
        Position_comp.velocity = vec2((input_x * PlayerController_comp.move_speed), Position_comp.velocity.y);
        Position_comp.pos = (Position_comp.pos + vec2((Position_comp.velocity.x * dt), 0.0f));
    });
}

void GravitySystem_tick(entt::registry& registry, float dt) {
    auto view = registry.view<Position, PlayerPhysics>();
    view.each([&](auto& Position_comp, auto& PlayerPhysics_comp) {
        if ((PlayerPhysics_comp.is_grounded == false)) {
            if ((jump_state == JumpState::WallSliding)) {
                Position_comp.velocity = vec2(Position_comp.velocity.x, PlayerPhysics_comp.wall_slide_speed);
            } else {
                Position_comp.velocity = vec2(Position_comp.velocity.x, (Position_comp.velocity.y + (PlayerPhysics_comp.gravity * dt)));
            }
        }
        Position_comp.pos = (Position_comp.pos + vec2(0.0f, (Position_comp.velocity.y * dt)));
    });
}

void JumpSystem_tick(entt::registry& registry, float dt) {
    auto view = registry.view<Position, PlayerPhysics, PlayerController>();
    view.each([&](auto& Position_comp, auto& PlayerPhysics_comp, auto& PlayerController_comp) {
        if (is_jump_pressed()) {
            if ((PlayerPhysics_comp.jumps_remaining > 0)) {
                Position_comp.velocity = vec2(Position_comp.velocity.x, (PlayerPhysics_comp.jump_force * -1.0f));
                PlayerPhysics_comp.jumps_remaining = (PlayerPhysics_comp.jumps_remaining - 1);
                PlayerPhysics_comp.is_grounded = false;
                PlayerController_comp.jump_state = JumpState::Jumping;
                PlayerJumped_buffer.push_back({Position_comp.pos, PlayerPhysics_comp.jumps_remaining});
            }
        }
        if (((Position_comp.velocity.y > 0.0f) && (PlayerController_comp.jump_state == JumpState::Jumping))) {
            PlayerController_comp.jump_state = JumpState::Falling;
        }
    });
}

void JumpSystem_PlayerLanded(entt::registry& registry, float position) {
    auto view = registry.view<Position, PlayerPhysics, PlayerController>();
    view.each([&](auto& Position_comp, auto& PlayerPhysics_comp, auto& PlayerController_comp) {
        PlayerPhysics_comp.is_grounded = true;
        PlayerPhysics_comp.jumps_remaining = PlayerPhysics_comp.max_jumps;
        PlayerController_comp.jump_state = JumpState::Grounded;
        Position_comp.velocity = vec2(Position_comp.velocity.x, 0.0f);
    });
}

void InvincibilitySystem_tick(entt::registry& registry, float dt) {
    auto view = registry.view<Health>();
    view.each([&](auto& Health_comp) {
        if ((Health_comp.invincible_timer > 0.0f)) {
            Health_comp.invincible_timer = (Health_comp.invincible_timer - dt);
        }
    });
}

void InvincibilitySystem_PlayerDamaged(entt::registry& registry, float amount) {
    auto view = registry.view<Health>();
    view.each([&](auto& Health_comp) {
        if ((Health_comp.invincible_timer <= 0.0f)) {
            Health_comp.health = (Health_comp.health - amount);
            Health_comp.invincible_timer = 1.5f;
            if ((Health_comp.health <= 0)) {
                Health_comp.lives = (Health_comp.lives - 1);
                Health_comp.health = Health_comp.max_health;
                PlayerDied_buffer.push_back({Health_comp.lives});
            }
        }
    });
}

void PatrolSystem_tick(entt::registry& registry, float dt) {
    auto view = registry.view<Position, EnemyAI>();
    view.each([&](auto& Position_comp, auto& EnemyAI_comp) {
        Position_comp.pos = (Position_comp.pos + vec2(((EnemyAI_comp.patrol_speed * EnemyAI_comp.direction) * dt), 0.0f));
        if ((Position_comp.pos.x >= EnemyAI_comp.patrol_max_x)) {
            EnemyAI_comp.direction = -1.0f;
            Position_comp.pos = vec2(EnemyAI_comp.patrol_max_x, Position_comp.pos.y);
        }
        if ((Position_comp.pos.x <= EnemyAI_comp.patrol_min_x)) {
            EnemyAI_comp.direction = 1.0f;
            Position_comp.pos = vec2(EnemyAI_comp.patrol_min_x, Position_comp.pos.y);
        }
    });
}

void CollectionSystem_tick(entt::registry& registry, float dt) {
    auto view = registry.view<Position, Collectible>();
    view.each([&](auto& Position_comp, auto& Collectible_comp) {
        if ((Collectible_comp.collected == false)) {
            auto player_pos = get_player_position();
            auto player_w = get_player_width();
            auto player_h = get_player_height();
            if ((abs_f((Position_comp.pos.x - player_pos.x)) < (Collectible_comp.gem_size + player_w))) {
                if ((abs_f((Position_comp.pos.y - player_pos.y)) < (Collectible_comp.gem_size + player_h))) {
                    Collectible_comp.collected = true;
                    GemCollected_buffer.push_back({Collectible_comp.point_value, Collectible_comp.gem_type, Position_comp.pos});
                }
            }
        }
    });
}

void ScoreSystem_GemCollected(entt::registry& registry, float point_value, float gem_type, float position) {
    auto view = registry.view<Score>();
    view.each([&](auto& Score_comp) {
        Score_comp.score = (Score_comp.score + point_value);
        Score_comp.gems_collected = (Score_comp.gems_collected + 1);
    });
}

void CameraFollowSystem_tick(entt::registry& registry, float dt) {
    auto view = registry.view<SideScrollCamera>();
    view.each([&](auto& SideScrollCamera_comp) {
        auto player_pos = get_player_position();
        auto target_x = (player_pos.x - SideScrollCamera_comp.offset_x);
        auto t = (SideScrollCamera_comp.smoothing * dt);
        if ((t > 1.0f)) {
            auto t = 1.0f;
        }
        SideScrollCamera_comp.cam_x = lerp(SideScrollCamera_comp.cam_x, target_x, t);
        SideScrollCamera_comp.cam_x = clamp_f(SideScrollCamera_comp.cam_x, SideScrollCamera_comp.min_x, SideScrollCamera_comp.max_x);
        set_camera_2d(SideScrollCamera_comp.cam_x, SideScrollCamera_comp.cam_y);
    });
}

void PlatformRenderer_tick(entt::registry& registry, float dt) {
    auto view = registry.view<Platform>();
    view.each([&](auto& Platform_comp) {
        draw_rect(Platform_comp.plat_pos, Platform_comp.plat_size, Platform_comp.plat_color);
    });
}

void EnemyRenderer_tick(entt::registry& registry, float dt) {
    auto view = registry.view<Position, EnemyAI>();
    view.each([&](auto& Position_comp, auto& EnemyAI_comp) {
        draw_rect(Position_comp.pos, vec2(EnemyAI_comp.enemy_width, EnemyAI_comp.enemy_height), EnemyAI_comp.enemy_color);
    });
}

void CollectibleRenderer_tick(entt::registry& registry, float dt) {
    auto view = registry.view<Position, Collectible>();
    view.each([&](auto& Position_comp, auto& Collectible_comp) {
        if ((Collectible_comp.collected == false)) {
            draw_rect(Position_comp.pos, vec2(Collectible_comp.gem_size, Collectible_comp.gem_size), Collectible_comp.gem_color);
        }
    });
}

// ── Entity Creation ─────────────────────────────────────────────────

entt::entity create_Player(entt::registry& registry) {
    auto entity = registry.create();
    registry.emplace<Position>(entity);
    registry.emplace<PlayerPhysics>(entity);
    registry.emplace<PlayerController>(entity);
    registry.emplace<Health>(entity);
    registry.emplace<Score>(entity);
    return entity;
}

entt::entity create_GroundPlatform(entt::registry& registry) {
    auto entity = registry.create();
    registry.emplace<Platform>(entity);
    return entity;
}

entt::entity create_FloatingPlatform1(entt::registry& registry) {
    auto entity = registry.create();
    registry.emplace<Platform>(entity);
    return entity;
}

entt::entity create_FloatingPlatform2(entt::registry& registry) {
    auto entity = registry.create();
    registry.emplace<Platform>(entity);
    return entity;
}

entt::entity create_FloatingPlatform3(entt::registry& registry) {
    auto entity = registry.create();
    registry.emplace<Platform>(entity);
    return entity;
}

entt::entity create_WalkerEnemy1(entt::registry& registry) {
    auto entity = registry.create();
    registry.emplace<Position>(entity);
    registry.emplace<EnemyAI>(entity);
    return entity;
}

entt::entity create_WalkerEnemy2(entt::registry& registry) {
    auto entity = registry.create();
    registry.emplace<Position>(entity);
    registry.emplace<EnemyAI>(entity);
    return entity;
}

entt::entity create_BlueGem1(entt::registry& registry) {
    auto entity = registry.create();
    registry.emplace<Position>(entity);
    registry.emplace<Collectible>(entity);
    return entity;
}

entt::entity create_BlueGem2(entt::registry& registry) {
    auto entity = registry.create();
    registry.emplace<Position>(entity);
    registry.emplace<Collectible>(entity);
    return entity;
}

entt::entity create_GoldGem1(entt::registry& registry) {
    auto entity = registry.create();
    registry.emplace<Position>(entity);
    registry.emplace<Collectible>(entity);
    return entity;
}

entt::entity create_CameraUnit(entt::registry& registry) {
    auto entity = registry.create();
    registry.emplace<SideScrollCamera>(entity);
    return entity;
}

// ── Event Dispatcher ────────────────────────────────────────────────

void setup_dispatcher(entt::dispatcher& dispatcher) {
    // dispatcher.sink<PlayerJumpedEvent>().connect<&on_PlayerJumped>();
    // dispatcher.sink<PlayerLandedEvent>().connect<&on_PlayerLanded>();
    // dispatcher.sink<PlayerDamagedEvent>().connect<&on_PlayerDamaged>();
    // dispatcher.sink<PlayerDiedEvent>().connect<&on_PlayerDied>();
    // dispatcher.sink<PlatformCollisionEvent>().connect<&on_PlatformCollision>();
    // dispatcher.sink<EnemyDefeatedEvent>().connect<&on_EnemyDefeated>();
    // dispatcher.sink<GemCollectedEvent>().connect<&on_GemCollected>();
}

// ── Main ────────────────────────────────────────────────────────────

int main() {
    InitWindow(1280, 720, "Cactus Platformer");
    SetTargetFPS(60);

    entt::registry registry;
    entt::dispatcher dispatcher;

    create_Player(registry);
    create_GroundPlatform(registry);
    create_FloatingPlatform1(registry);
    create_FloatingPlatform2(registry);
    create_FloatingPlatform3(registry);
    create_WalkerEnemy1(registry);
    create_WalkerEnemy2(registry);
    create_BlueGem1(registry);
    create_BlueGem2(registry);
    create_GoldGem1(registry);
    create_CameraUnit(registry);

    while (!WindowShouldClose()) {
        float dt = GetFrameTime();

        MovementSystem_tick(registry, dt);
        GravitySystem_tick(registry, dt);
        JumpSystem_tick(registry, dt);
        InvincibilitySystem_tick(registry, dt);
        PatrolSystem_tick(registry, dt);
        CollectionSystem_tick(registry, dt);
        CameraFollowSystem_tick(registry, dt);
        PlatformRenderer_tick(registry, dt);
        EnemyRenderer_tick(registry, dt);
        CollectibleRenderer_tick(registry, dt);
        dispatcher.update();

        BeginDrawing();
        ClearBackground(RAYWHITE);
        EndDrawing();
    }

    CloseWindow();
    return 0;
}
