#include <catch2/catch_test_macros.hpp>

#include "backends/cpp-entt/component_emitter.h"
#include "backends/cpp-entt/cpp_entt_codegen.h"
#include "backends/cpp-entt/event_emitter.h"
#include "backends/cpp-entt/system_emitter.h"
#include "common/error_reporter.h"
#include "frontend/lexer.h"
#include "frontend/parser.h"
#include "frontend/semantic_analyzer.h"

using namespace cactus;

static DecoratedProgram full_pipeline(const std::string& source, ProgramNode& program_out) {
    ErrorReporter errors;
    Lexer lexer(source, "test.cactus", errors);
    auto tokens = lexer.tokenize();
    REQUIRE_FALSE(errors.has_errors());
    Parser parser(std::move(tokens), errors);
    program_out = parser.parse_program();
    REQUIRE_FALSE(errors.has_errors());
    SemanticAnalyzer analyzer(errors);
    auto result = analyzer.analyze(program_out);
    REQUIRE_FALSE(errors.has_errors());
    return result;
}

TEST_CASE("Codegen EnTT: component struct from trait", "[codegen-entt]") {
    ResolvedTrait trait;
    trait.name = "Position";
    trait.fields.push_back({"x", {TypeKind::Float, "float"}, false, true, false, false, false});
    trait.fields.push_back({"y", {TypeKind::Float, "float"}, false, true, false, false, false});

    auto code = EnttComponentEmitter::emit_component(trait);
    CHECK(code.find("struct Position") != std::string::npos);
    CHECK(code.find("float x{}") != std::string::npos);
    CHECK(code.find("float y{}") != std::string::npos);
    // Should NOT have std::vector (that's SoA)
    CHECK(code.find("std::vector") == std::string::npos);
}

TEST_CASE("Codegen EnTT: registry view system", "[codegen-entt]") {
    ProgramNode program;
    auto decorated = full_pipeline(
        "trait Pos:\n    var x: float\n    var y: float\n"
        "system Move:\n    filter: [Pos]\n    on tick(dt: float):\n        x = x + dt\n",
        program);

    for (auto& decl : program.declarations) {
        if (auto* sys = std::get_if<SystemNode>(&decl)) {
            auto code = EnttSystemEmitter::emit_system(*sys, decorated);
            CHECK(code.find("void Move_tick") != std::string::npos);
            CHECK(code.find("entt::registry& registry") != std::string::npos);
            CHECK(code.find("registry.view<Pos>()") != std::string::npos);
            CHECK(code.find("view.each") != std::string::npos);
        }
    }
}

TEST_CASE("Codegen EnTT: event struct", "[codegen-entt]") {
    ProgramNode program;
    auto decorated = full_pipeline(
        "event Damage:\n    var amount: int\n",
        program);

    for (auto& decl : program.declarations) {
        if (auto* event = std::get_if<EventNode>(&decl)) {
            auto code = EnttEventEmitter::emit_event(*event, decorated);
            CHECK(code.find("struct DamageEvent") != std::string::npos);
            CHECK(code.find("int amount;") != std::string::npos);

            auto sink = EnttEventEmitter::emit_sink_connection(*event);
            CHECK(sink.find("dispatcher.sink<DamageEvent>") != std::string::npos);
        }
    }
}

TEST_CASE("Codegen EnTT: full pipeline", "[codegen-entt]") {
    ProgramNode program;
    auto decorated = full_pipeline(
        "trait Pos:\n    persist sync var x: float\n    persist sync var y: float\n"
        "system Move:\n    filter: [Pos]\n    on tick(dt: float):\n        x = x + dt\n",
        program);

    auto code = CppEnttCodegen::generate(decorated);

    CHECK(code.find("Generated by Cactus DSL Compiler (cpp-entt backend)") != std::string::npos);
    CHECK(code.find("#include <entt/entt.hpp>") != std::string::npos);
    CHECK(code.find("#include \"raylib.h\"") != std::string::npos);
    CHECK(code.find("struct Pos") != std::string::npos);
    CHECK(code.find("entt::registry registry") != std::string::npos);
    CHECK(code.find("entt::dispatcher dispatcher") != std::string::npos);
    CHECK(code.find("int main()") != std::string::npos);
    CHECK(code.find("InitWindow") != std::string::npos);

    // Persist hooks
    CHECK(code.find("save_Pos") != std::string::npos);
    CHECK(code.find("load_Pos") != std::string::npos);

    // Sync hooks
    CHECK(code.find("replicate_Pos") != std::string::npos);
}

TEST_CASE("Codegen EnTT: entity creation from unit", "[codegen-entt]") {
    ProgramNode program;
    auto decorated = full_pipeline(
        "trait Pos:\n    var x: float\n    var y: float\n"
        "trait Health:\n    var hp: int\n"
        "unit Player:\n    apply:\n        Pos\n        Health\n",
        program);

    auto code = CppEnttCodegen::generate(decorated);
    CHECK(code.find("create_Player") != std::string::npos);
    CHECK(code.find("registry.create()") != std::string::npos);
    CHECK(code.find("registry.emplace<Pos>") != std::string::npos);
    CHECK(code.find("registry.emplace<Health>") != std::string::npos);
}
