#include <catch2/catch_test_macros.hpp>

#include "backends/cpp-manual/cpp_manual_codegen.h"
#include "backends/cpp-manual/event_emitter.h"
#include "backends/cpp-manual/soa_emitter.h"
#include "backends/cpp-manual/system_emitter.h"
#include "common/error_reporter.h"
#include "frontend/lexer.h"
#include "frontend/parser.h"
#include "frontend/semantic_analyzer.h"

using namespace cactus;

static DecoratedProgram full_pipeline(const std::string& source, ProgramNode& program_out) {
    ErrorReporter errors;
    Lexer lexer(source, "test.cactus", errors);
    auto tokens = lexer.tokenize();
    REQUIRE_FALSE(errors.has_errors());
    Parser parser(std::move(tokens), errors);
    program_out = parser.parse_program();
    REQUIRE_FALSE(errors.has_errors());
    SemanticAnalyzer analyzer(errors);
    auto result = analyzer.analyze(program_out);
    REQUIRE_FALSE(errors.has_errors());
    return result;
}

TEST_CASE("Codegen Manual: SoA storage from trait", "[codegen-manual]") {
    ResolvedTrait trait;
    trait.name = "Position";
    trait.fields.push_back({"x", {TypeKind::Float, "float"}, false, true, false, false, false});
    trait.fields.push_back({"y", {TypeKind::Float, "float"}, false, true, false, false, false});

    auto code = SoaEmitter::emit_soa_storage(trait);
    CHECK(code.find("struct PositionStorage") != std::string::npos);
    CHECK(code.find("std::vector<float> x;") != std::string::npos);
    CHECK(code.find("std::vector<float> y;") != std::string::npos);
    CHECK(code.find("size_t count") != std::string::npos);
}

TEST_CASE("Codegen Manual: POD struct", "[codegen-manual]") {
    ResolvedStruct s;
    s.name = "Item";
    s.fields.push_back({"price", {TypeKind::Int, "int"}});
    s.fields.push_back({"weight", {TypeKind::Float, "float"}});

    auto code = SoaEmitter::emit_pod_struct(s);
    CHECK(code.find("struct Item") != std::string::npos);
    CHECK(code.find("int price;") != std::string::npos);
    CHECK(code.find("float weight;") != std::string::npos);
}

TEST_CASE("Codegen Manual: enum generation", "[codegen-manual]") {
    ResolvedEnum e;
    e.name = "Color";
    e.variants = {"Red", "Green", "Blue"};

    auto code = SoaEmitter::emit_enum(e);
    CHECK(code.find("enum class Color") != std::string::npos);
    CHECK(code.find("Red") != std::string::npos);
    CHECK(code.find("Green") != std::string::npos);
    CHECK(code.find("Blue") != std::string::npos);
}

TEST_CASE("Codegen Manual: type_to_cpp mapping", "[codegen-manual]") {
    CHECK(SoaEmitter::type_to_cpp({TypeKind::Int, "int"}) == "int");
    CHECK(SoaEmitter::type_to_cpp({TypeKind::Float, "float"}) == "float");
    CHECK(SoaEmitter::type_to_cpp({TypeKind::Bool, "bool"}) == "bool");
    CHECK(SoaEmitter::type_to_cpp({TypeKind::String, "string"}) == "std::string");
    CHECK(SoaEmitter::type_to_cpp({TypeKind::EntityId, "entity_id"}) == "uint32_t");
    CHECK(SoaEmitter::type_to_cpp({TypeKind::Struct, "Item"}) == "Item");
}

TEST_CASE("Codegen Manual: system loop generation", "[codegen-manual]") {
    ProgramNode program;
    auto decorated = full_pipeline(
        "trait Pos:\n    var x: float\n    var y: float\n"
        "system Move:\n    filter: [Pos]\n    on tick(dt: float):\n        x = x + dt\n",
        program);

    // Find the system node
    for (auto& decl : program.declarations) {
        if (auto* sys = std::get_if<SystemNode>(&decl)) {
            auto code = ManualSystemEmitter::emit_system(*sys, decorated);
            CHECK(code.find("void Move_tick") != std::string::npos);
            CHECK(code.find("PosStorage&") != std::string::npos);
            CHECK(code.find("for (size_t i = 0;") != std::string::npos);
        }
    }
}

TEST_CASE("Codegen Manual: full pipeline generates compilable structure", "[codegen-manual]") {
    ProgramNode program;
    auto decorated = full_pipeline(
        "trait Pos:\n    persist sync var x: float\n    persist sync var y: float\n"
        "system Move:\n    filter: [Pos]\n    on tick(dt: float):\n        x = x + dt\n",
        program);

    auto code = CppManualCodegen::generate(decorated);

    // Check structure
    CHECK(code.find("Generated by Cactus DSL Compiler") != std::string::npos);
    CHECK(code.find("#include <vector>") != std::string::npos);
    CHECK(code.find("#include \"raylib.h\"") != std::string::npos);
    CHECK(code.find("PosStorage") != std::string::npos);
    CHECK(code.find("int main()") != std::string::npos);
    CHECK(code.find("InitWindow") != std::string::npos);
    CHECK(code.find("CloseWindow") != std::string::npos);

    // Persist hooks
    CHECK(code.find("save_Pos") != std::string::npos);
    CHECK(code.find("load_Pos") != std::string::npos);

    // Sync hooks
    CHECK(code.find("replicate_Pos") != std::string::npos);
}

TEST_CASE("Codegen Manual: event buffer generation", "[codegen-manual]") {
    ProgramNode program;
    auto decorated = full_pipeline(
        "event Damage:\n    var amount: int\n    var source: int\n",
        program);

    for (auto& decl : program.declarations) {
        if (auto* event = std::get_if<EventNode>(&decl)) {
            auto code = ManualEventEmitter::emit_event(*event, decorated);
            CHECK(code.find("struct DamageEvent") != std::string::npos);
            CHECK(code.find("int amount;") != std::string::npos);
            CHECK(code.find("Damage_buffer") != std::string::npos);

            auto dispatch = ManualEventEmitter::emit_dispatch(*event);
            CHECK(dispatch.find("dispatch_Damage") != std::string::npos);
        }
    }
}
