#include "backends/cpp-entt/cpp_entt_codegen.h"

#include "backends/cpp-entt/component_emitter.h"
#include "backends/cpp-entt/event_emitter.h"
#include "backends/cpp-entt/system_emitter.h"
#include "backends/cpp-manual/soa_emitter.h"

#include <algorithm>
#include <cctype>
#include <optional>
#include <sstream>

namespace cactus {

namespace {
// Task 6.1: Check if the program has any extern funcs requiring the runtime header
bool has_extern_funcs(const DecoratedProgram& program) {
    for (const auto& [name, func] : program.funcs) { // NOLINT(readability-use-anyofallof)
        if (func.is_extern) {
            return true;
        }
    }
    return false;
}

bool has_trait(const DecoratedProgram& program, const std::string& name) {
    return program.traits.find(name) != program.traits.end();
}

std::string upper_copy(std::string value) {
    std::transform(value.begin(), value.end(), value.begin(),
                   [](unsigned char c) { return static_cast<char>(std::toupper(c)); });
    return value;
}

std::optional<std::string> raylib_key_constant(const ExprNode& expr) {
    if (const auto* member = std::get_if<MemberExpr>(&expr.expr)) {
        if (const auto* ident = std::get_if<IdentExpr>(&member->object->expr)) {
            if (ident->name == "Key") {
                return "KEY_" + upper_copy(member->member);
            }
        }
    }
    return std::nullopt;
}
}  // namespace

std::string CppEnttCodegen::generate(const DecoratedProgram& program) { // NOLINT(readability-function-cognitive-complexity)
    std::ostringstream out;

    // Header
    out << "// Generated by Cactus DSL Compiler (cpp-entt backend)\n\n";
    out << "#include <entt/entt.hpp>\n";
    out << "#include <raylib.h>\n";
    out << "\n";
    out << "#include <cstdint>\n";
    out << "#include <string>\n";
    out << "#include <unordered_set>\n";
    out << "#include <vector>\n";
    // Task 6.2: Include runtime header when extern funcs are present
    if (has_extern_funcs(program)) {
        out << "#include \"cactus_runtime.h\"\n";
    }
    out << "\n";

    // Helper: vec2() constructor mapped to Vector2
    out << "inline Vector2 vec2(float x, float y) {\n";
    out << "    return {x, y};\n";
    out << "}\n\n";

    // Built-in runtime helpers for generated examples
    out << "struct tickEvent {\n";
    out << "    float dt;\n";
    out << "};\n";
    out << "using TickEvent = tickEvent;\n\n";

    if (program.ast != nullptr) {
        bool has_axis_input = false;
        for (const auto& decl : program.ast->declarations) {
            if (const auto* input = std::get_if<InputDeclNode>(&decl)) {
                has_axis_input = has_axis_input || input->input_kind == InputKind::Axis;
            }
        }

        if (has_axis_input) {
            out << "enum class InputAction {\n";
            bool first = true;
            for (const auto& decl : program.ast->declarations) {
                if (const auto* input = std::get_if<InputDeclNode>(&decl)) {
                    if (input->input_kind != InputKind::Axis) {
                        continue;
                    }
                    out << (first ? "    " : ",\n    ") << input->name;
                    first = false;
                }
            }
            out << "\n};\n\n";

            for (const auto& decl : program.ast->declarations) {
                if (const auto* input = std::get_if<InputDeclNode>(&decl)) {
                    if (input->input_kind != InputKind::Axis) {
                        continue;
                    }
                    out << "constexpr InputAction " << input->name << " = InputAction::" << input->name << ";\n";
                }
            }
            out << "\n";

            out << "static float cactus_axis(InputAction action) {\n";
            out << "    switch (action) {\n";
            for (const auto& decl : program.ast->declarations) {
                if (const auto* input = std::get_if<InputDeclNode>(&decl)) {
                    if (input->input_kind != InputKind::Axis) {
                        continue;
                    }
                    std::string negative = "0";
                    std::string positive = "0";
                    for (const auto& prop : input->props) {
                        if (prop.key == "negative") {
                            if (auto key = raylib_key_constant(*prop.value)) {
                                negative = "(IsKeyDown(" + *key + ") ? 1.0f : 0.0f)";
                            }
                        } else if (prop.key == "positive") {
                            if (auto key = raylib_key_constant(*prop.value)) {
                                positive = "(IsKeyDown(" + *key + ") ? 1.0f : 0.0f)";
                            }
                        }
                    }
                    out << "        case InputAction::" << input->name << ": return " << positive << " - " << negative << ";\n";
                }
            }
            out << "    }\n";
            out << "    return 0.0f;\n";
            out << "}\n\n";

            out << "struct inputEvent {\n";
            out << "    float axis(InputAction action) const { return cactus_axis(action); }\n";
            out << "};\n\n";
        }
    }

    if (program.ast != nullptr) {
        for (const auto& decl : program.ast->declarations) {
            if (const auto* cb = std::get_if<ConstBlockNode>(&decl)) {
                for (const auto& ca : cb->assignments) {
                    out << "constexpr auto " << ca.name << " = " << ManualSystemEmitter::emit_expr(*ca.value) << ";\n";
                }
            }
        }
        out << "\n";
    }

    // Enums
    for (const auto& [name, e] : program.enums) {
        auto emitted_code = EnttComponentEmitter::emit_enum(e);
        if (!emitted_code.empty()) {
            out << emitted_code << "\n";
        }
    }

    // POD structs
    for (const auto& [name, s] : program.structs) {
        out << EnttComponentEmitter::emit_pod_struct(s) << "\n";
    }

    // Component structs (from traits)
    for (const auto& [name, t] : program.traits) {
        out << EnttComponentEmitter::emit_component(t) << "\n";
    }

    // Events
    if (program.ast != nullptr) {
        for (auto& decl : program.ast->declarations) {
            if (auto* event = std::get_if<EventNode>(&decl)) {
                out << EnttEventEmitter::emit_event(*event, program) << "\n";
            }
        }
    }

    out << EnttSystemEmitter::emit_entt_hierarchy_helpers(program);

    // Persist serialization stubs
    out << "// ── Persist Serialization ────────────────────────────────────────────\n\n";
    for (const auto& [name, t] : program.traits) {
        bool has_persist = false;
        for (const auto& f : t.fields) {
            if (f.is_persist) { has_persist = true; break; }
        }
        if (has_persist) {
            out << "void save_" << name << "(const " << name << "& comp) {\n";
            for (const auto& f : t.fields) {
                if (f.is_persist) {
                    out << "    // serialize comp." << f.name << "\n";
                }
            }
            out << "}\n\n";
            out << "void load_" << name << "(" << name << "& comp) {\n";
            for (const auto& f : t.fields) {
                if (f.is_persist) {
                    out << "    // deserialize into comp." << f.name << "\n";
                }
            }
            out << "}\n\n";
        }
    }

    // Sync replication stubs
    out << "// ── Sync Replication ─────────────────────────────────────────────────\n\n";
    for (const auto& [name, t] : program.traits) {
        bool has_sync = false;
        for (const auto& f : t.fields) {
            if (f.is_sync) { has_sync = true; break; }
        }
        if (has_sync) {
            out << "void replicate_" << name << "(const " << name << "& comp) {\n";
            for (const auto& f : t.fields) {
                if (f.is_sync) {
                    out << "    // send delta for comp." << f.name << "\n";
                }
            }
            out << "}\n\n";
        }
    }

    // System functions
    if (program.ast != nullptr) {
        out << "// ── Systems ─────────────────────────────────────────────────────────\n\n";
        for (auto& decl : program.ast->declarations) {
            if (auto* sys = std::get_if<SystemNode>(&decl)) {
                out << EnttSystemEmitter::emit_system(*sys, program);
            }
            if (auto* sys = std::get_if<ExternSystemNode>(&decl)) {
                out << EnttSystemEmitter::emit_extern_system(*sys, program);
            }
        }
    }

    // Entity creation from units
    if (program.ast != nullptr) {
        out << "// ── Entity Creation ─────────────────────────────────────────────────\n\n";
        for (auto& decl : program.ast->declarations) {
            if (auto* unit = std::get_if<UnitNode>(&decl)) {
                out << "entt::entity create_" << unit->name << "(entt::registry& registry) {\n";
                out << "    auto entity = registry.create();\n";
                for (const auto& trait : unit->traits) {
                    out << "    {\n";
                    out << "        auto component = " << trait.trait_name << "{};\n";
                    for (const auto& assignment : trait.assignments) {
                        out << "        component." << assignment.name << " = "
                            << ManualSystemEmitter::emit_expr(*assignment.value) << ";\n";
                    }
                    out << "        registry.emplace<" << trait.trait_name << ">(entity, component);\n";
                    out << "    }\n";
                }
                out << "    return entity;\n";
                out << "}\n\n";
            }
        }
    }

    // Dispatcher setup
    if (program.ast != nullptr) {
        out << "// ── Event Dispatcher ────────────────────────────────────────────────\n\n";
        out << "void setup_dispatcher(entt::dispatcher& dispatcher) {\n";
        out << "    (void)dispatcher;\n";
        for (auto& decl : program.ast->declarations) {
            if (auto* event = std::get_if<EventNode>(&decl)) {
                out << "    " << EnttEventEmitter::emit_sink_connection(*event);
            }
        }
        out << "}\n\n";
    }

    // Main game loop — extract window constants from const block if available
    std::string win_width = "800";
    std::string win_height = "600";
    std::string win_title = "\"Cactus Game\"";
    std::string win_fps = "60";
    if (program.ast != nullptr) {
        for (auto& decl : program.ast->declarations) {
            if (auto* cb = std::get_if<ConstBlockNode>(&decl)) {
                for (auto& ca : cb->assignments) {
                    if (ca.name == "WINDOW_WIDTH") {
                        win_width = ManualSystemEmitter::emit_expr(*ca.value);
                    } else if (ca.name == "WINDOW_HEIGHT") {
                        win_height = ManualSystemEmitter::emit_expr(*ca.value);
                    } else if (ca.name == "WINDOW_TITLE") {
                        win_title = ManualSystemEmitter::emit_expr(*ca.value);
                    } else if (ca.name == "TARGET_FPS") {
                        win_fps = ManualSystemEmitter::emit_expr(*ca.value);
                    }
                }
            }
        }
    }

    out << "// ── Main ────────────────────────────────────────────────────────────\n\n";
    out << "// NOLINTNEXTLINE(bugprone-exception-escape)\n";
    out << "int main() noexcept {\n";
    out << "    InitWindow(" << win_width << ", " << win_height << ", " << win_title << ");\n";
    out << "    SetTargetFPS(" << win_fps << ");\n\n";
    out << "    entt::registry registry;\n";
    out << "    entt::dispatcher dispatcher;\n\n";

    // Create entities from units
    if (program.ast != nullptr) {
        for (auto& decl : program.ast->declarations) {
            if (auto* unit = std::get_if<UnitNode>(&decl)) {
                out << "    create_" << unit->name << "(registry);\n";
            }
        }
        out << "\n";
    }

    out << "    while (!WindowShouldClose()) {\n";

    bool emits_tick_handler = false;
    if (program.ast != nullptr) {
        for (auto& decl : program.ast->declarations) {
            if (auto* sys = std::get_if<SystemNode>(&decl)) {
                for (auto& handler : sys->handlers) {
                    if (handler.event_name == "tick") {
                        emits_tick_handler = true;
                        break;
                    }
                }
            }
            if (emits_tick_handler) {
                break;
            }
        }
    }

    if (emits_tick_handler) {
        out << "        float dt = GetFrameTime();\n\n";
    } else {
        out << "        GetFrameTime();\n\n";
    }

    // Call system input handlers
    if (program.ast != nullptr) {
        bool emits_input_handler = false;
        for (auto& decl : program.ast->declarations) {
            if (auto* sys = std::get_if<SystemNode>(&decl)) {
                for (auto& handler : sys->handlers) {
                    if (handler.event_name == "input") {
                        emits_input_handler = true;
                        break;
                    }
                }
            }
            if (emits_input_handler) {
                break;
            }
        }
        if (emits_input_handler) {
            out << "        auto input = inputEvent{};\n";
            for (auto& decl : program.ast->declarations) {
                if (auto* sys = std::get_if<SystemNode>(&decl)) {
                    for (auto& handler : sys->handlers) {
                        if (handler.event_name == "input") {
                            out << "        " << sys->name << "_input(registry, input);\n";
                        }
                    }
                }
            }
            out << "\n";
        }
    }

    // Call system tick handlers
    if (program.ast != nullptr) {
        for (auto& decl : program.ast->declarations) {
            if (auto* sys = std::get_if<SystemNode>(&decl)) {
                for (auto& handler : sys->handlers) {
                    if (handler.event_name == "tick") {
                        out << "        " << sys->name << "_tick(registry, tickEvent{dt});\n";
                    }
                }
            }
            if (auto* sys = std::get_if<ExternSystemNode>(&decl)) {
                out << "        " << sys->name << "_tick(registry);\n";
            }
        }
    }

    out << "        dispatcher.update();\n\n";
    out << "        BeginDrawing();\n";
    out << "        ClearBackground(RAYWHITE);\n";
    if (has_trait(program, "Position")) {
        out << "        {\n";
        out << "            auto draw_view = registry.view<Position>();\n";
        out << "            draw_view.each([&](const Position& pos) {\n";
        out << "                DrawRectangle(static_cast<int>(pos.x), static_cast<int>(pos.y), 50, 50, Color{100, 149, 237, 255});\n";
        out << "            });\n";
        out << "        }\n";
    }
    out << "        EndDrawing();\n";
    out << "    }\n\n";
    out << "    CloseWindow();\n";
    out << "    return 0;\n";
    out << "}\n";

    return out.str();
}

}  // namespace cactus
