#include "backends/cpp-entt/cpp_entt_codegen.h"

#include "backends/cpp-entt/component_emitter.h"
#include "backends/cpp-entt/event_emitter.h"
#include "backends/cpp-entt/system_emitter.h"
#include "backends/cpp-manual/soa_emitter.h"

#include <algorithm>
#include <cctype>
#include <optional>
#include <sstream>

namespace cactus {

namespace {
// Task 6.1: Check if the program has any extern funcs requiring the runtime header
bool has_extern_funcs(const DecoratedProgram& program) {
    for (const auto& [name, func] : program.funcs) { // NOLINT(readability-use-anyofallof)
        if (func.is_extern) {
            return true;
        }
    }
    return false;
}

std::string upper_copy(std::string value) {
    std::ranges::transform(value, value.begin(), [](unsigned char c) { return static_cast<char>(std::toupper(c)); });
    return value;
}

std::string snake_case(std::string value) {
    std::string result;
    for (size_t i = 0; i < value.size(); ++i) {
        const char ch = value[i];
        if (std::isupper(static_cast<unsigned char>(ch)) != 0) {
            if (!result.empty() && result.back() != '_') {
                result += '_';
            }
            result += static_cast<char>(std::tolower(static_cast<unsigned char>(ch)));
        } else {
            result += ch;
        }
    }
    return result;
}

std::string system_function_name(const std::string& system_name, const std::string& suffix) {
    return snake_case(system_name) + "_" + suffix;
}

std::string input_action_constant_name(const std::string& input_name) {
    return "K_" + upper_copy(snake_case(input_name));
}

std::optional<std::string> raylib_key_constant(const ExprNode& expr) {
    if (const auto* member = std::get_if<MemberExpr>(&expr.expr)) {
        if (const auto* ident = std::get_if<IdentExpr>(&member->object->expr)) {
            if (ident->name == "Key") {
                return "KEY_" + upper_copy(member->member);
            }
        }
    }
    return std::nullopt;
}

std::optional<std::string> raylib_mouse_constant(const ExprNode& expr) {
    if (const auto* member = std::get_if<MemberExpr>(&expr.expr)) {
        if (const auto* ident = std::get_if<IdentExpr>(&member->object->expr)) {
            if (ident->name == "MouseButton") {
                return "MOUSE_BUTTON_" + upper_copy(snake_case(member->member));
            }
        }
    }
    return std::nullopt;
}

std::string pad_to_width(const std::string& value, std::size_t width) {
    if (value.size() >= width) {
        return value;
    }
    return value + std::string(width - value.size(), ' ');
}
}  // namespace

std::string CppEnttCodegen::generate(const DecoratedProgram& program) { // NOLINT(readability-function-cognitive-complexity)
    std::ostringstream out;

    // Header
    out << "// Generated by Cactus DSL Compiler (cpp-entt backend)\n\n";
    out << "#include \"backends/cpp-entt/runtime.h\"\n";
    out << "\n";
    out << "#include <entt/entt.hpp>\n";
    out << "#include <raylib.h>\n";
    out << "\n";
    out << "#include <cstdint>\n";
    out << "#include <string>\n";
    out << "#include <unordered_set>\n";
    out << "#include <vector>\n";
    // Task 6.2: Include runtime header when extern funcs are present
    if (has_extern_funcs(program)) {
        out << "#include \"cactus_runtime.h\"\n";
    }
    out << "\n";

    // Helper: vec2() constructor mapped to Vector2
    out << "inline Vector2 vec2(float x, float y) {\n";
    out << "    return Vector2{.x = x, .y = y};\n";
    out << "}\n\n";

    // Built-in runtime helpers for generated examples
    out << "struct TickEvent {\n";
    out << "    float dt;\n";
    out << "};\n";
    out << "\n";

    if (program.ast != nullptr) {
        bool has_axis_input = false;
        bool has_button_input = false;
        for (const auto& decl : program.ast->declarations) {
            if (const auto* input = std::get_if<InputDeclNode>(&decl)) {
                has_axis_input = has_axis_input || input->input_kind == InputKind::Axis;
                has_button_input = has_button_input || input->input_kind == InputKind::Button;
            }
        }

        if (has_button_input) {
            out << "using InputButton = std::uint8_t;\n";
            std::uint8_t button_index = 0;
            for (const auto& decl : program.ast->declarations) {
                if (const auto* input = std::get_if<InputDeclNode>(&decl)) {
                    if (input->input_kind != InputKind::Button) {
                        continue;
                    }
                    out << "constexpr InputButton " << input_action_constant_name(input->name)
                        << " = static_cast<InputButton>(" << static_cast<int>(button_index++) << ");\n";
                }
            }
            out << "\n";

            out << "static int cactus_input_button_key(InputButton button) {\n";
            out << "    switch (button) {\n";
            button_index = 0;
            for (const auto& decl : program.ast->declarations) {
                if (const auto* input = std::get_if<InputDeclNode>(&decl)) {
                    if (input->input_kind != InputKind::Button) {
                        continue;
                    }
                    std::string key = "0";
                    for (const auto& prop : input->props) {
                        if (prop.key == "key") {
                            if (auto maybe_key = raylib_key_constant(*prop.value)) {
                                key = *maybe_key;
                            } else if (auto maybe_mouse = raylib_mouse_constant(*prop.value)) {
                                key = *maybe_mouse;
                            }
                        }
                    }
                    out << "        case static_cast<InputButton>(" << static_cast<int>(button_index++) << "): return " << key << ";\n";
                }
            }
            out << "    }\n";
            out << "    return 0;\n";
            out << "}  // namespace cactus::runtime::entt_backend\n\n";

            out << "namespace cactus::runtime::entt_backend {\n";
            out << "[[nodiscard]] bool pressed(InputButton button) noexcept {\n";
            out << "    return IsKeyPressed(cactus_input_button_key(button));\n";
            out << "}\n";
            out << "[[nodiscard]] bool down(InputButton button) noexcept {\n";
            out << "    return IsKeyDown(cactus_input_button_key(button));\n";
            out << "}\n";
            out << "[[nodiscard]] bool released(InputButton button) noexcept {\n";
            out << "    return IsKeyReleased(cactus_input_button_key(button));\n";
            out << "}\n";
            out << "}  // namespace cactus::runtime::entt_backend\n\n";
        }

        if (has_axis_input) {
            out << "using InputAxis = std::uint8_t;\n";
            out << "enum class CactusInputAxisTag : std::uint8_t { ";
            bool first = true;
            for (const auto& decl : program.ast->declarations) {
                if (const auto* input = std::get_if<InputDeclNode>(&decl)) {
                    if (input->input_kind != InputKind::Axis) {
                        continue;
                    }
                    out << (first ? "" : ", ") << input->name;
                    first = false;
                }
            }
            out << " };\n\n";

            for (const auto& decl : program.ast->declarations) {
                if (const auto* input = std::get_if<InputDeclNode>(&decl)) {
                    if (input->input_kind != InputKind::Axis) {
                        continue;
                    }
                    out << "constexpr InputAxis " << input_action_constant_name(input->name)
                        << " = static_cast<InputAxis>(CactusInputAxisTag::" << input->name << ");\n";
                }
            }
            out << "\n";

            out << "static float cactus_axis(InputAxis action) {\n";
            out << "    switch (action) {\n";
            for (const auto& decl : program.ast->declarations) {
                if (const auto* input = std::get_if<InputDeclNode>(&decl)) {
                    if (input->input_kind != InputKind::Axis) {
                        continue;
                    }
                    std::string negative = "0";
                    std::string positive = "0";
                    for (const auto& prop : input->props) {
                        if (prop.key == "negative") {
                            if (auto key = raylib_key_constant(*prop.value)) {
                                negative = "(IsKeyDown(" + *key + ") ? 1.0F : 0.0F)";
                            }
                        } else if (prop.key == "positive") {
                            if (auto key = raylib_key_constant(*prop.value)) {
                                positive = "(IsKeyDown(" + *key + ") ? 1.0F : 0.0F)";
                            }
                        }
                    }
                    out << "        case static_cast<InputAxis>(CactusInputAxisTag::" << input->name << "):\n";
                    out << "            return " << positive << " - " << negative << ";\n";
                }
            }
            out << "        default:\n";
            out << "            return 0.0F;\n";
            out << "    }\n";
            out << "}\n\n";

            out << "namespace cactus::runtime::entt_backend {\n";
            out << "[[nodiscard]] float axis(InputAxis action) noexcept {\n";
            out << "    return cactus_axis(action);\n";
            out << "}\n";
            out << "[[nodiscard]] Vector2 axis2(InputAxis x, InputAxis y) noexcept {\n";
            out << "    return Vector2{.x = axis(x), .y = axis(y)};\n";
            out << "}\n";
            out << "}  // namespace cactus::runtime::entt_backend\n\n";
        }

        if (has_axis_input || has_button_input) {
            out << "struct InputEvent {\n";
            if (has_axis_input) {
                out << "    [[nodiscard]] static float axis(InputAxis action) {\n";
                out << "        return cactus::runtime::entt_backend::axis(action);\n";
                out << "    }\n";
            }
            out << "};\n\n";
        }
    }

    if (program.ast != nullptr) {
        for (const auto& decl : program.ast->declarations) {
            if (const auto* cb = std::get_if<ConstBlockNode>(&decl)) {
                for (const auto& ca : cb->assignments) {
                    out << "constexpr auto " << upper_copy(ca.name) << " = " << ManualSystemEmitter::emit_expr(*ca.value) << ";\n";
                }
            }
        }
        out << "\n";
    }

    // Enums
    for (const auto& [name, e] : program.enums) {
        auto emitted_code = EnttComponentEmitter::emit_enum(e);
        if (!emitted_code.empty()) {
            out << emitted_code << "\n";
        }
    }

    // POD structs
    for (const auto& [name, s] : program.structs) {
        out << EnttComponentEmitter::emit_pod_struct(s) << "\n";
    }

    // Component structs (from traits)
    for (const auto& [name, t] : program.traits) {
        out << EnttComponentEmitter::emit_component(t) << "\n";
    }

    // Events
    if (program.ast != nullptr) {
        for (auto& decl : program.ast->declarations) {
            if (auto* event = std::get_if<EventNode>(&decl)) {
                out << EnttEventEmitter::emit_event(*event, program) << "\n";
            }
        }
    }

    out << EnttSystemEmitter::emit_entt_hierarchy_helpers(program);

    // Persist serialization stubs
    out << "// ── Persist Serialization ────────────────────────────────────────────\n\n";
    for (const auto& [name, t] : program.traits) {
        bool has_persist = false;
        for (const auto& f : t.fields) {
            if (f.is_persist) { has_persist = true; break; }
        }
        if (has_persist) {
            out << "void save_" << name << "(const " << name << "& comp) {\n";
            for (const auto& f : t.fields) {
                if (f.is_persist) {
                    out << "    // serialize comp." << f.name << "\n";
                }
            }
            out << "}\n\n";
            out << "void load_" << name << "(" << name << "& comp) {\n";
            for (const auto& f : t.fields) {
                if (f.is_persist) {
                    out << "    // deserialize into comp." << f.name << "\n";
                }
            }
            out << "}\n\n";
        }
    }

    // Sync replication stubs
    out << "// ── Sync Replication ─────────────────────────────────────────────────\n\n";
    for (const auto& [name, t] : program.traits) {
        bool has_sync = false;
        for (const auto& f : t.fields) {
            if (f.is_sync) { has_sync = true; break; }
        }
        if (has_sync) {
            out << "void replicate_" << name << "(const " << name << "& comp) {\n";
            for (const auto& f : t.fields) {
                if (f.is_sync) {
                    out << "    // send delta for comp." << f.name << "\n";
                }
            }
            out << "}\n\n";
        }
    }

    // System functions
    if (program.ast != nullptr) {
        out << "// ── Systems ─────────────────────────────────────────────────────────\n\n";
        for (auto& decl : program.ast->declarations) {
            if (auto* sys = std::get_if<SystemNode>(&decl)) {
                out << EnttSystemEmitter::emit_system(*sys, program);
            }
            if (auto* sys = std::get_if<ExternSystemNode>(&decl)) {
                out << EnttSystemEmitter::emit_extern_system(*sys, program);
            }
        }
    }

    // Entity creation from units
    if (program.ast != nullptr) {
        out << "// ── Entity Creation ─────────────────────────────────────────────────\n\n";
        for (auto& decl : program.ast->declarations) {
            if (auto* unit = std::get_if<UnitNode>(&decl)) {
                out << "entt::entity create_" << snake_case(unit->name) << "(entt::registry& registry) {\n";
                out << "    auto entity = registry.create();\n";
                for (const auto& trait : unit->traits) {
                    out << "    {\n";
                    std::size_t widest = std::string("auto component").size();
                    for (const auto& assignment : trait.assignments) {
                        widest = std::max(widest, std::string("component.").size() + assignment.name.size());
                    }
                    out << "        " << pad_to_width("auto component", widest) << " = " << trait.trait_name << "{};\n";
                    for (const auto& assignment : trait.assignments) {
                        out << "        " << pad_to_width("component." + assignment.name, widest) << " = "
                            << ManualSystemEmitter::emit_expr(*assignment.value) << ";\n";
                    }
                    out << "        registry.emplace<" << trait.trait_name << ">(entity, component);\n";
                    out << "    }\n";
                }
                out << "    return entity;\n";
                out << "}\n\n";
            }
        }
    }

    // Dispatcher setup
    out << "// ── Event Dispatcher ────────────────────────────────────────────────\n\n";
    out << "namespace cactus::runtime::entt_backend {\n\n";
    out << "void generated_setup_dispatcher(entt::dispatcher& dispatcher) {\n";
    if (program.ast != nullptr) {
        out << "    (void)dispatcher;\n";
        for (auto& decl : program.ast->declarations) {
            if (auto* event = std::get_if<EventNode>(&decl)) {
                out << "    " << EnttEventEmitter::emit_sink_connection(*event);
            }
        }
    }
    out << "}\n\n";

    // Main game loop — extract window constants from const block if available
    std::string win_width = "800";
    std::string win_height = "600";
    std::string win_title = "\"Cactus Game\"";
    std::string win_fps = "60";
    if (program.ast != nullptr) {
        for (auto& decl : program.ast->declarations) {
            if (auto* cb = std::get_if<ConstBlockNode>(&decl)) {
                for (auto& ca : cb->assignments) {
                    if (ca.name == "WINDOW_WIDTH") {
                        win_width = ManualSystemEmitter::emit_expr(*ca.value);
                    } else if (ca.name == "WINDOW_HEIGHT") {
                        win_height = ManualSystemEmitter::emit_expr(*ca.value);
                    } else if (ca.name == "WINDOW_TITLE") {
                        win_title = ManualSystemEmitter::emit_expr(*ca.value);
                    } else if (ca.name == "TARGET_FPS") {
                        win_fps = ManualSystemEmitter::emit_expr(*ca.value);
                    }
                }
            }
        }
    }

    out << "// ── Runtime Glue ────────────────────────────────────────────────────\n\n";
    out << "ProjectConfig generated_project_config() noexcept {\n";
    out << "    return {.window_width = " << win_width
        << ", .window_height = " << win_height
        << ", .window_title = " << win_title
        << ", .target_fps = " << win_fps << "};\n";
    out << "}\n\n";

    out << "void generated_init_project(entt::registry& registry) {\n";
    if (program.ast != nullptr) {
        for (auto& decl : program.ast->declarations) {
            if (auto* unit = std::get_if<UnitNode>(&decl)) {
                out << "    create_" << snake_case(unit->name) << "(registry);\n";
            }
        }
    }
    out << "}\n\n";

    out << "void generated_update_project(entt::registry& registry, entt::dispatcher& dispatcher, float dt) {\n";

    bool emits_tick_handler = false;
    if (program.ast != nullptr) {
        for (auto& decl : program.ast->declarations) {
            if (auto* sys = std::get_if<SystemNode>(&decl)) {
                for (auto& handler : sys->handlers) {
                    if (handler.event_name == "tick") {
                        emits_tick_handler = true;
                        break;
                    }
                }
            }
            if (emits_tick_handler) {
                break;
            }
        }
    }

    if (emits_tick_handler) {
        out << "    (void)dt;\n\n";
    } else {
        out << "    (void)dt;\n\n";
    }

    // Call system input handlers
    if (program.ast != nullptr) {
        bool emits_input_handler = false;
        for (auto& decl : program.ast->declarations) {
            if (auto* sys = std::get_if<SystemNode>(&decl)) {
                for (auto& handler : sys->handlers) {
                    if (handler.event_name == "input") {
                        emits_input_handler = true;
                        break;
                    }
                }
            }
            if (emits_input_handler) {
                break;
            }
        }
        if (emits_input_handler) {
            out << "    auto input = InputEvent{};\n";
            for (auto& decl : program.ast->declarations) {
                if (auto* sys = std::get_if<SystemNode>(&decl)) {
                    for (auto& handler : sys->handlers) {
                        if (handler.event_name == "input") {
                            out << "    " << system_function_name(sys->name, "input") << "(registry, input);\n";
                        }
                    }
                }
            }
            out << "\n";
        }
    }

    // Call non-render system tick handlers
    if (program.ast != nullptr) {
        for (auto& decl : program.ast->declarations) {
            if (auto* sys = std::get_if<SystemNode>(&decl)) {
                for (auto& handler : sys->handlers) {
                    if (handler.event_name == "tick") {
                        out << "    " << system_function_name(sys->name, "tick") << "(registry, TickEvent{dt});\n";
                    }
                }
            }
            if (auto* sys = std::get_if<ExternSystemNode>(&decl)) {
                if (sys->name == "ShapeRenderer") {
                    continue;
                }
                out << "    " << system_function_name(sys->name, "tick") << "(registry);\n";
            }
        }
    }

    out << "    dispatcher.update();\n";
    out << "}\n\n";

    out << "void generated_render_project(entt::registry& registry, entt::dispatcher& dispatcher) {\n";
    out << "    (void)dispatcher;\n";
    if (program.ast != nullptr) {
        for (auto& decl : program.ast->declarations) {
            if (auto* sys = std::get_if<ExternSystemNode>(&decl)) {
                if (sys->name == "ShapeRenderer") {
                    out << "    " << system_function_name(sys->name, "tick") << "(registry);\n";
                }
            }
        }
    }
    out << "}\n";
    out << "\n}  // namespace cactus::runtime::entt_backend\n";

    return out.str();
}

}  // namespace cactus
