#include "backends/cpp-entt/cpp_entt_codegen.h"

#include "backends/cpp-entt/component_emitter.h"
#include "backends/cpp-entt/event_emitter.h"
#include "backends/cpp-entt/system_emitter.h"
#include "backends/cpp-manual/soa_emitter.h"

#include <sstream>

namespace cactus {

namespace {
// Task 6.1: Check if the program has any extern funcs requiring the runtime header
bool has_extern_funcs(const DecoratedProgram& program) {
    for (const auto& [name, func] : program.funcs) { // NOLINT(readability-use-anyofallof)
        if (func.is_extern) {
            return true;
        }
    }
    return false;
}
}  // namespace

std::string CppEnttCodegen::generate(const DecoratedProgram& program) { // NOLINT(readability-function-cognitive-complexity)
    std::ostringstream out;

    // Header
    out << "// Generated by Cactus DSL Compiler (cpp-entt backend)\n";
    out << "#pragma once\n\n";
    out << "#include <cstdint>\n";
    out << "#include <string>\n";
    out << "#include <vector>\n";
    out << "#include <entt/entt.hpp>\n";
    out << "#include \"raylib.h\"\n";
    // Task 6.2: Include runtime header when extern funcs are present
    if (has_extern_funcs(program)) {
        out << "#include \"cactus_runtime.h\"\n";
    }
    out << "\n";

    // Helper: vec2() constructor mapped to Vector2
    out << "inline Vector2 vec2(float x, float y) { return {x, y}; }\n\n";

    // Enums
    for (const auto& [name, e] : program.enums) {
        out << EnttComponentEmitter::emit_enum(e) << "\n";
    }

    // POD structs
    for (const auto& [name, s] : program.structs) {
        out << EnttComponentEmitter::emit_pod_struct(s) << "\n";
    }

    // Component structs (from traits)
    for (const auto& [name, t] : program.traits) {
        out << EnttComponentEmitter::emit_component(t) << "\n";
    }

    // Events
    if (program.ast != nullptr) {
        for (auto& decl : program.ast->declarations) {
            if (auto* event = std::get_if<EventNode>(&decl)) {
                out << EnttEventEmitter::emit_event(*event, program) << "\n";
            }
        }
    }

    // Persist serialization stubs
    out << "// ── Persist Serialization ────────────────────────────────────────────\n\n";
    for (const auto& [name, t] : program.traits) {
        bool has_persist = false;
        for (const auto& f : t.fields) {
            if (f.is_persist) { has_persist = true; break; }
        }
        if (has_persist) {
            out << "void save_" << name << "(const " << name << "& comp) {\n";
            for (const auto& f : t.fields) {
                if (f.is_persist) {
                    out << "    // serialize comp." << f.name << "\n";
                }
            }
            out << "}\n\n";
            out << "void load_" << name << "(" << name << "& comp) {\n";
            for (const auto& f : t.fields) {
                if (f.is_persist) {
                    out << "    // deserialize into comp." << f.name << "\n";
                }
            }
            out << "}\n\n";
        }
    }

    // Sync replication stubs
    out << "// ── Sync Replication ─────────────────────────────────────────────────\n\n";
    for (const auto& [name, t] : program.traits) {
        bool has_sync = false;
        for (const auto& f : t.fields) {
            if (f.is_sync) { has_sync = true; break; }
        }
        if (has_sync) {
            out << "void replicate_" << name << "(const " << name << "& comp) {\n";
            for (const auto& f : t.fields) {
                if (f.is_sync) {
                    out << "    // send delta for comp." << f.name << "\n";
                }
            }
            out << "}\n\n";
        }
    }

    // System functions
    if (program.ast != nullptr) {
        out << "// ── Systems ─────────────────────────────────────────────────────────\n\n";
        for (auto& decl : program.ast->declarations) {
            if (auto* sys = std::get_if<SystemNode>(&decl)) {
                out << EnttSystemEmitter::emit_system(*sys, program);
            }
        }
    }

    // Entity creation from units
    if (program.ast != nullptr) {
        out << "// ── Entity Creation ─────────────────────────────────────────────────\n\n";
        for (auto& decl : program.ast->declarations) {
            if (auto* unit = std::get_if<UnitNode>(&decl)) {
                out << "entt::entity create_" << unit->name << "(entt::registry& registry) {\n";
                out << "    auto entity = registry.create();\n";
                for (const auto& trait : unit->traits) {
                    out << "    registry.emplace<" << trait.trait_name << ">(entity);\n";
                }
                out << "    return entity;\n";
                out << "}\n\n";
            }
        }
    }

    // Dispatcher setup
    if (program.ast != nullptr) {
        out << "// ── Event Dispatcher ────────────────────────────────────────────────\n\n";
        out << "void setup_dispatcher(entt::dispatcher& dispatcher) {\n";
        for (auto& decl : program.ast->declarations) {
            if (auto* event = std::get_if<EventNode>(&decl)) {
                out << "    " << EnttEventEmitter::emit_sink_connection(*event);
            }
        }
        out << "}\n\n";
    }

    // Main game loop — extract window constants from const block if available
    std::string win_width = "800";
    std::string win_height = "600";
    std::string win_title = "\"Cactus Game\"";
    std::string win_fps = "60";
    if (program.ast != nullptr) {
        for (auto& decl : program.ast->declarations) {
            if (auto* cb = std::get_if<ConstBlockNode>(&decl)) {
                for (auto& ca : cb->assignments) {
                    if (ca.name == "WINDOW_WIDTH") {
                        win_width = ManualSystemEmitter::emit_expr(*ca.value);
                    } else if (ca.name == "WINDOW_HEIGHT") {
                        win_height = ManualSystemEmitter::emit_expr(*ca.value);
                    } else if (ca.name == "WINDOW_TITLE") {
                        win_title = ManualSystemEmitter::emit_expr(*ca.value);
                    } else if (ca.name == "TARGET_FPS") {
                        win_fps = ManualSystemEmitter::emit_expr(*ca.value);
                    }
                }
            }
        }
    }

    out << "// ── Main ────────────────────────────────────────────────────────────\n\n";
    out << "int main() {\n";
    out << "    InitWindow(" << win_width << ", " << win_height << ", " << win_title << ");\n";
    out << "    SetTargetFPS(" << win_fps << ");\n\n";
    out << "    entt::registry registry;\n";
    out << "    entt::dispatcher dispatcher;\n\n";

    // Create entities from units
    if (program.ast != nullptr) {
        for (auto& decl : program.ast->declarations) {
            if (auto* unit = std::get_if<UnitNode>(&decl)) {
                out << "    create_" << unit->name << "(registry);\n";
            }
        }
        out << "\n";
    }

    out << "    while (!WindowShouldClose()) {\n";
    out << "        float dt = GetFrameTime();\n\n";

    // Call system tick handlers
    if (program.ast != nullptr) {
        for (auto& decl : program.ast->declarations) {
            if (auto* sys = std::get_if<SystemNode>(&decl)) {
                for (auto& handler : sys->handlers) {
                    if (handler.event_name == "tick") {
                        out << "        " << sys->name << "_tick(registry, dt);\n";
                    }
                }
            }
        }
    }

    out << "        dispatcher.update();\n\n";
    out << "        BeginDrawing();\n";
    out << "        ClearBackground(RAYWHITE);\n";
    out << "        EndDrawing();\n";
    out << "    }\n\n";
    out << "    CloseWindow();\n";
    out << "    return 0;\n";
    out << "}\n";

    return out.str();
}

}  // namespace cactus
