#include "backends/cpp-manual/cpp_manual_codegen.h"

#include "backends/cpp-manual/event_emitter.h"
#include "backends/cpp-manual/soa_emitter.h"
#include "backends/cpp-manual/system_emitter.h"

#include <sstream>

namespace cactus {

std::string CppManualCodegen::generate(const DecoratedProgram& program) {
    std::ostringstream out;

    // Header
    out << "// Generated by Cactus DSL Compiler (cpp-manual backend)\n";
    out << "#pragma once\n\n";
    out << "#include <cstdint>\n";
    out << "#include <string>\n";
    out << "#include <vector>\n";
    out << "#include \"raylib.h\"\n\n";

    // Enums
    for (auto& [name, e] : program.enums) {
        out << SoaEmitter::emit_enum(e) << "\n";
    }

    // POD structs
    for (auto& [name, s] : program.structs) {
        out << SoaEmitter::emit_pod_struct(s) << "\n";
    }

    // SoA storage classes
    for (auto& [name, t] : program.traits) {
        out << SoaEmitter::emit_soa_storage(t) << "\n";
    }

    // Events
    if (program.ast) {
        for (auto& decl : program.ast->declarations) {
            if (auto* event = std::get_if<EventNode>(&decl)) {
                out << ManualEventEmitter::emit_event(*event, program);
                out << ManualEventEmitter::emit_dispatch(*event);
            }
        }
    }

    // Persist serialization stubs
    out << "// ── Persist Serialization ────────────────────────────────────────────\n\n";
    for (auto& [name, t] : program.traits) {
        bool has_persist = false;
        for (auto& f : t.fields) {
            if (f.is_persist) { has_persist = true; break; }
        }
        if (has_persist) {
            out << "void save_" << name << "(const " << name << "Storage& store, size_t idx) {\n";
            for (auto& f : t.fields) {
                if (f.is_persist) {
                    out << "    // serialize store." << f.name << "[idx]\n";
                }
            }
            out << "}\n\n";
            out << "void load_" << name << "(" << name << "Storage& store, size_t idx) {\n";
            for (auto& f : t.fields) {
                if (f.is_persist) {
                    out << "    // deserialize into store." << f.name << "[idx]\n";
                }
            }
            out << "}\n\n";
        }
    }

    // Sync replication stubs
    out << "// ── Sync Replication ─────────────────────────────────────────────────\n\n";
    for (auto& [name, t] : program.traits) {
        bool has_sync = false;
        for (auto& f : t.fields) {
            if (f.is_sync) { has_sync = true; break; }
        }
        if (has_sync) {
            out << "void replicate_" << name << "(const " << name << "Storage& store, size_t idx) {\n";
            for (auto& f : t.fields) {
                if (f.is_sync) {
                    out << "    // send delta for store." << f.name << "[idx]\n";
                }
            }
            out << "}\n\n";
        }
    }

    // System functions
    if (program.ast) {
        out << "// ── Systems ─────────────────────────────────────────────────────────\n\n";
        for (auto& decl : program.ast->declarations) {
            if (auto* sys = std::get_if<SystemNode>(&decl)) {
                out << ManualSystemEmitter::emit_system(*sys, program);
            }
        }
    }

    // Main game loop
    out << "// ── Main ────────────────────────────────────────────────────────────\n\n";
    out << "int main() {\n";
    out << "    InitWindow(800, 600, \"Cactus Game\");\n";
    out << "    SetTargetFPS(60);\n\n";

    // Instantiate storages
    for (auto& [name, t] : program.traits) {
        out << "    " << name << "Storage " << name << "_store;\n";
    }
    out << "\n";

    out << "    while (!WindowShouldClose()) {\n";
    out << "        float dt = GetFrameTime();\n\n";

    // Call system tick handlers
    if (program.ast) {
        for (auto& decl : program.ast->declarations) {
            if (auto* sys = std::get_if<SystemNode>(&decl)) {
                for (auto& handler : sys->handlers) {
                    if (handler.event_name == "tick") {
                        out << "        " << sys->name << "_tick(";
                        for (size_t i = 0; i < sys->filter.trait_names.size(); ++i) {
                            if (i > 0) out << ", ";
                            out << sys->filter.trait_names[i] << "_store";
                        }
                        out << ", dt);\n";
                    }
                }
            }
        }
    }

    out << "\n";
    out << "        BeginDrawing();\n";
    out << "        ClearBackground(RAYWHITE);\n";
    out << "        EndDrawing();\n";
    out << "    }\n\n";
    out << "    CloseWindow();\n";
    out << "    return 0;\n";
    out << "}\n";

    return out.str();
}

}  // namespace cactus
